service:
  port:
    name: http
    l4_protocol: TCP
    port: 8080
    targetPort: 8080
  label: batch-service-1-hqsovj4kuk
  name: batch-service-1-hqsovj4kuk
  selector: batch-service-1-hqsovj4kuk
  type:
  - ClusterIP
  - NodePort
namespace: -@namespace@-
batch:
  name: batch-service-1-hqsovj4kuk
  image:
    name: batch-service-1-hqsovj4kuk
    tag: lastest
    secret: -@repoSecret@-
  container:
    name: batch-service-1-hqsovj4kuk
  repo:
    url: -@imageRepoName@-
  backing: 
    pobdb:
      name: secret-postgresql-service-2-za7gvof1s4
    subdb:
      name: secret-postgresql-service-1-w7lhhgjbfi

  volume:
    name: pvc-batch-service-1-hqsovj4kuk
  resource:
    request:
      memory: -@requestMemory@-
      cpu: -@requestCpu@-
    limits:
      memory: -@limitsMemory@-
      cpu: -@limitsCpu@-
pvc:
  name: pvc-batch-service-1-hqsovj4kuk
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
